name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator # USed above in signature, "outputs: random-number: value: ..."
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run ls "\\il1dtoutinfs001.kcura.corp\outsideinshare\Results\Branches" >> $GITHUB_OUTPUT
      shell: bash
    # - run: goodbye.sh # always fails due to not being truly executable
    #   shell: bash
