name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: echo $(pwd)
      shell: bash
    - run: date
      shell: bash
    - run: Get-Verb -Verb S* | Format-List
      shell: pwsh

    # FROM: https://github.com/marketplace/actions/azure-cli-action
    - name: Check Azure version
      uses: azure/CLI@v1
      with:
        # azcliversion: 2.30.0
        inlineScript: 
          az --version

#     Gotten from: https://github.com/relativityone/get-keyvault-secrets-action/tree/main#single-secret
#      - uses: azure/login@v1
#        with:
#          creds: ${{ secrets.AZURE_CREDENTIALS }}

#      - uses: relativityone/get-keyvault-secrets-action@v0
#        id: secret
#        with:
#          key-vault: my-key-vault
#          secrets: my-secret

#      - name: assert non null
#        run: |
#          [[ ! -z "${{ steps.secret.outputs.my-secret }}" ]] && echo "Not empty"

#    Gotten from: https://github.com/marketplace/actions/azure-cli-action
#    - name: Azure LoginS
#      uses: azure/login@v1
#      with:
#        creds: ${{ secrets.AZURE_CREDENTIALS }}

#    - name: Azure CLI script
#      uses: azure/CLI@v1
#      with:
#        azcliversion: 2.30.0
#        inlineScript: |
#          az account show
#          az storage -h

    # Experiments show that the following code is beyond the capacity of GitHubActions YAML to parse
    # - run ls //il1dtoutinfs001.kcura.corp/outsideinshare/Results/Branches
    #   shell: bash
